/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module f51m(i0, i1, i2, i3, i4, i5, i6, i7, o0, o1, o2, o3, o4, o5, o6, o7);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input i4;
  wire i4;
  input i5;
  wire i5;
  input i6;
  wire i6;
  input i7;
  wire i7;
  output o0;
  wire o0;
  output o1;
  wire o1;
  output o2;
  wire o2;
  output o3;
  wire o3;
  output o4;
  wire o4;
  output o5;
  wire o5;
  output o6;
  wire o6;
  output o7;
  wire o7;
  sky130_fd_sc_hd__inv_2 _43_ (
    .A(i7),
    .Y(o7)
  );
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(i3),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_2 _45_ (
    .A(i1),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_2 _46_ (
    .A(i5),
    .Y(_02_)
  );
  sky130_fd_sc_hd__or2_2 _47_ (
    .A(i2),
    .B(i4),
    .X(_03_)
  );
  sky130_fd_sc_hd__and2_2 _48_ (
    .A(i2),
    .B(i4),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_2 _49_ (
    .A(i2),
    .B(i4),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and2b_2 _50_ (
    .A_N(i2),
    .B(i7),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand2_2 _51_ (
    .A(i3),
    .B(i4),
    .Y(_07_)
  );
  sky130_fd_sc_hd__or3b_2 _52_ (
    .A(i7),
    .B(i4),
    .C_N(i2),
    .X(_08_)
  );
  sky130_fd_sc_hd__o311a_2 _53_ (
    .A1(i6),
    .A2(_05_),
    .A3(_06_),
    .B1(_07_),
    .C1(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2_2 _54_ (
    .A(i3),
    .B(_04_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21a_2 _55_ (
    .A1(i5),
    .A2(_04_),
    .B1(_03_),
    .X(_11_)
  );
  sky130_fd_sc_hd__o221a_2 _56_ (
    .A1(_02_),
    .A2(_09_),
    .B1(_11_),
    .B2(i3),
    .C1(_10_),
    .X(_12_)
  );
  sky130_fd_sc_hd__nand2_2 _57_ (
    .A(i4),
    .B(i6),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21a_2 _58_ (
    .A1(i7),
    .A2(i4),
    .B1(i6),
    .X(_14_)
  );
  sky130_fd_sc_hd__a2111o_2 _59_ (
    .A1(_03_),
    .A2(_14_),
    .B1(_11_),
    .C1(_00_),
    .D1(i1),
    .X(_15_)
  );
  sky130_fd_sc_hd__and2_2 _60_ (
    .A(i3),
    .B(i1),
    .X(_16_)
  );
  sky130_fd_sc_hd__nor3b_2 _61_ (
    .A(i3),
    .B(i1),
    .C_N(i5),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o211a_2 _62_ (
    .A1(_16_),
    .A2(_17_),
    .B1(_03_),
    .C1(_14_),
    .X(_18_)
  );
  sky130_fd_sc_hd__nand2_2 _63_ (
    .A(i7),
    .B(i5),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a31o_2 _64_ (
    .A1(i7),
    .A2(i4),
    .A3(i5),
    .B1(_04_),
    .X(_20_)
  );
  sky130_fd_sc_hd__a31oi_2 _65_ (
    .A1(_00_),
    .A2(_01_),
    .A3(_20_),
    .B1(_18_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o211ai_2 _66_ (
    .A1(_01_),
    .A2(_12_),
    .B1(_15_),
    .C1(_21_),
    .Y(o1)
  );
  sky130_fd_sc_hd__and2_2 _67_ (
    .A(i3),
    .B(i5),
    .X(_22_)
  );
  sky130_fd_sc_hd__o21a_2 _68_ (
    .A1(i7),
    .A2(i3),
    .B1(i5),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor2_2 _69_ (
    .A(i3),
    .B(i5),
    .Y(_24_)
  );
  sky130_fd_sc_hd__o21a_2 _70_ (
    .A1(i3),
    .A2(i5),
    .B1(i6),
    .X(_25_)
  );
  sky130_fd_sc_hd__nand2b_2 _71_ (
    .A_N(_25_),
    .B(_04_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a31o_2 _72_ (
    .A1(i7),
    .A2(i3),
    .A3(i6),
    .B1(_03_),
    .X(_27_)
  );
  sky130_fd_sc_hd__a21o_2 _73_ (
    .A1(_26_),
    .A2(_27_),
    .B1(_23_),
    .X(_28_)
  );
  sky130_fd_sc_hd__or4_2 _74_ (
    .A(i3),
    .B(i2),
    .C(i6),
    .D(_19_),
    .X(_29_)
  );
  sky130_fd_sc_hd__nor2_2 _75_ (
    .A(_14_),
    .B(_22_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__or3_2 _76_ (
    .A(_05_),
    .B(_24_),
    .C(_30_),
    .X(_31_)
  );
  sky130_fd_sc_hd__and3_2 _77_ (
    .A(_28_),
    .B(_29_),
    .C(_31_),
    .X(o2)
  );
  sky130_fd_sc_hd__nand2b_2 _78_ (
    .A_N(i4),
    .B(i5),
    .Y(_32_)
  );
  sky130_fd_sc_hd__mux2_1 _79_ (
    .A0(_32_),
    .A1(i5),
    .S(i6),
    .X(_33_)
  );
  sky130_fd_sc_hd__xnor2_2 _80_ (
    .A(i3),
    .B(_33_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21ai_2 _81_ (
    .A1(_22_),
    .A2(_24_),
    .B1(_13_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o31a_2 _82_ (
    .A1(_13_),
    .A2(_22_),
    .A3(_24_),
    .B1(o7),
    .X(_36_)
  );
  sky130_fd_sc_hd__a22o_2 _83_ (
    .A1(i7),
    .A2(_34_),
    .B1(_35_),
    .B2(_36_),
    .X(o3)
  );
  sky130_fd_sc_hd__mux2_1 _84_ (
    .A0(_19_),
    .A1(i7),
    .S(i6),
    .X(_37_)
  );
  sky130_fd_sc_hd__xnor2_2 _85_ (
    .A(i4),
    .B(_37_),
    .Y(o4)
  );
  sky130_fd_sc_hd__o21bai_2 _86_ (
    .A1(o7),
    .A2(i6),
    .B1_N(i5),
    .Y(_38_)
  );
  sky130_fd_sc_hd__o21a_2 _87_ (
    .A1(i6),
    .A2(_19_),
    .B1(_38_),
    .X(o5)
  );
  sky130_fd_sc_hd__xor2_2 _88_ (
    .A(i7),
    .B(i6),
    .X(o6)
  );
  sky130_fd_sc_hd__a2111oi_2 _89_ (
    .A1(i7),
    .A2(_25_),
    .B1(_22_),
    .C1(_16_),
    .D1(i4),
    .Y(_39_)
  );
  sky130_fd_sc_hd__o21ai_2 _90_ (
    .A1(i3),
    .A2(i1),
    .B1(i2),
    .Y(_40_)
  );
  sky130_fd_sc_hd__o221a_2 _91_ (
    .A1(i3),
    .A2(i1),
    .B1(_23_),
    .B2(_25_),
    .C1(i4),
    .X(_41_)
  );
  sky130_fd_sc_hd__o32a_2 _92_ (
    .A1(i2),
    .A2(_16_),
    .A3(_41_),
    .B1(_40_),
    .B2(_39_),
    .X(_42_)
  );
  sky130_fd_sc_hd__xor2_2 _93_ (
    .A(i0),
    .B(_42_),
    .X(o0)
  );
endmodule
