// Auto-generated by LibreLane
module alu3(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input i0,
  input i1,
  input i2,
  input i3,
  input i4,
  input i5,
  input i6,
  input i7,
  input i8,
  input i9,
  output o0,
  output o1,
  output o2,
  output o3,
  output o4,
  output o5,
  output o6,
  output o7
);
endmodule
