compile_gtech:
	ghdl -a --std=08 --work=gtech_lib and2_d.vhd
	ghdl -a --std=08 --work=gtech_lib or2_d.vhd
	ghdl -a --std=08 --work=gtech_lib xor2_d.vhd
	ghdl -a --std=08 --work=gtech_lib not_d.vhd
	ghdl -a --std=08 --work=gtech_lib nand2_d.vhd
	ghdl -a --std=08 --work=gtech_lib nor2_d.vhd
	ghdl -a --std=08 --work=gtech_lib buffer_d.vhd
 
clean:
	rm ./*.o
	rm ./*.cf
