/* Generated by Netenos */
 
module xor5(i0,i1,i2,i3,i4,o0);
	input i0;
	input i1;
	input i2;
	input i3;
	input i4;
	output o0;
	wire w0;
	wire w1;
	wire w2;
	wire w3;
	wire w4;
	wire w5;
	wire w6;
	wire w7;
	wire w8;
	sky130_fd_sc_hd__xor2_2 _3_ (
		.A(w0),
		.B(w1),
		.X(w6)
	);
	sky130_fd_sc_hd__xor2_2 _4_ (
		.A(w2),
		.B(w3),
		.X(w5)
	);
	sky130_fd_sc_hd__xnor2_2 _5_ (
		.A(w4),
		.B(w5),
		.Y(w7)
	);
	sky130_fd_sc_hd__xnor2_2 _6_ (
		.A(w6),
		.B(w7),
		.Y(w8)
	);
endmodule
