/* Generated by Netenos */
 
module xor5(i0,i1,i2,i3,i4,o0);
	input i0;
	input i1;
	input i2;
	input i3;
	input i4;
	output o0;
	wire _0_;
	wire _1_;
	wire _2_;
	wire i0;
	wire i1;
	wire i2;
	wire i3;
	wire i4;
	wire o0;
	sky130_fd_sc_hd__xor2_2 _3_ (
		.A(i0),
		.B(i2),
		.X(_0_)
	);
	sky130_fd_sc_hd__xor2_2 _4_ (
		.A(i1),
		.B(i3),
		.X(_1_)
	);
	sky130_fd_sc_hd__xnor2_2 _5_ (
		.A(i4),
		.B(_1_),
		.Y(_2_)
	);
	sky130_fd_sc_hd__xnor2_2 _6_ (
		.A(_0_),
		.B(_2_),
		.Y(o0)
	);
endmodule
