require 'erb'

require_relative "./converter/code.rb"
require_relative "./converter/dotgen.rb"
require_relative "./converter/netson.rb"
require_relative "./converter/convVhdl2Netlist.rb"
require_relative "./converter/convNetlist2Vhdl.rb"
require_relative "./converter/convNetlist2Matrix.rb"
require_relative "./converter/genStim2.rb"
require_relative "./converter/genTestbench.rb"
require_relative "./converter/vhdlCompileScript.rb"
require_relative "./converter/genCompTestbench.rb"
require_relative "./converter/convBlif2Netlist.rb"
require_relative "./converter/convNetlist2Blif.rb"
require_relative "./converter/convNetlist2Bench.rb"