require_relative "netlist.rb"
require_relative "converter.rb"
require_relative "interface.rb"
require_relative "inserter/tamper.rb"
require_relative "vcd.rb"
require_relative "atetaAddOn.rb"
require_relative "serializer/serdes.rb"
# require_relative "experiments/experimenter.rb"