compile_gtech:
	ghdl -a --std=08 --work=gtech_lib buffer_d.vhd
	ghdl -a --std=08 --work=gtech_lib not_d.vhd
	ghdl -a --std=08 --work=gtech_lib xor5_d.vhd
	ghdl -a --std=08 --work=gtech_lib xor4_d.vhd
	ghdl -a --std=08 --work=gtech_lib xor3_d.vhd
	ghdl -a --std=08 --work=gtech_lib xor2_d.vhd
	ghdl -a --std=08 --work=gtech_lib nor5_d.vhd
	ghdl -a --std=08 --work=gtech_lib nor4_d.vhd
	ghdl -a --std=08 --work=gtech_lib nor3_d.vhd
	ghdl -a --std=08 --work=gtech_lib nor2_d.vhd
	ghdl -a --std=08 --work=gtech_lib nand5_d.vhd
	ghdl -a --std=08 --work=gtech_lib nand4_d.vhd
	ghdl -a --std=08 --work=gtech_lib nand3_d.vhd
	ghdl -a --std=08 --work=gtech_lib nand2_d.vhd
	ghdl -a --std=08 --work=gtech_lib or5_d.vhd
	ghdl -a --std=08 --work=gtech_lib or4_d.vhd
	ghdl -a --std=08 --work=gtech_lib or3_d.vhd
	ghdl -a --std=08 --work=gtech_lib or2_d.vhd
	ghdl -a --std=08 --work=gtech_lib and5_d.vhd
	ghdl -a --std=08 --work=gtech_lib and4_d.vhd
	ghdl -a --std=08 --work=gtech_lib and3_d.vhd
	ghdl -a --std=08 --work=gtech_lib and2_d.vhd
 
clean:
	rm ./*.o
	rm ./*.cf
