module Converter
  class GenVTestbench 

    def initialize nl
      @nl_data = data_extraction(nl)
    end

    def data_extraction netlist
      { 
        entity_name: netlist.name,
        inputs: netlist.get_inputs.collect{|p| p.name},
        outputs: netlist.get_outputs.collect{|p| p.name}
      }
    end

    def gen_testbench circ_name, stim_file, clk_period = 5, path: "", full_traces: false
      @engine = ERB.new(IO.read("#{File.dirname(__FILE__)}/tb_templates/tb_template.v"))

      # total_cycles = # Calculer le nombre de vecteurs de test dans le stim_file 
      # bin_vec_stim = # Déterminer la valeur de cette variable dans le stim_file
      tb_entity_name = "tb_#{circ_name}"
      path = "#{tb_entity_name}.v" if path == ""
      bin_vec_stim, stim_cycles = extract_stim_file_info(stim_file).values_at(
        :bin_vec_stim, 
        :stim_cycles
      )
      total_cycles= stim_cycles + 8
      nb_inputs   = @nl_data[:inputs].length
      nb_outputs  = @nl_data[:outputs].length
      
      src = @engine.result(binding)
      File.write(path, src)
    end

    def extract_stim_file_info stim_file
      
      header = `head -n 1 #{stim_file}`.chomp.split(';')
      if header[0] == '# Stimuli sequence'
        {
          bin_vec_stim: (header[1] == 'bin'),
          stim_cycles: `grep -vc "^#" #{stim_file}`.chomp.to_i
        }
      else
        raise "Error: Only stim files generated by Netenos are handled."
      end 
    end
  end
end