/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module test_sdf(i0, i1, i2, i3, i4, o0,o1);
  wire _0_;
  wire _1_;
  wire _2_;
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input i4;
  wire i4;
  output o0;
  wire o0;
  sky130_fd_sc_hd__xnor3_1 _2_ (
    .A(i1),
    .B(i0),
    .C(i2),
    .X(_0_)
  );
  sky130_fd_sc_hd__xor2_1 _3_ (
    .A(i3),
    .B(i4),
    .X(_1_)
  );
  sky130_fd_sc_hd__xor2_1 _4_ (
    .A(_0_),
    .B(_1_),
    .X(o0)
  );
endmodule
